---
- name: Create SSH Key Pair and Copy Public Key to Remote Server
  hosts: all
  gather_facts: true

  tasks:
    - name: Check if SSH key pair already exists
      delegate_to: localhost
      ansible.builtin.stat:
        path: ~/.ssh/id_rsa_ansible
      register: ssh_key_exists

    - name: Generate SSH key pair if it doesn't exist
      delegate_to: localhost
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_rsa_ansible
        type: rsa
        size: 2048
      when: not ssh_key_exists.stat.exists

    # - name: Run ssh-copy-id to copy the SSH public key
    #   delegate_to: localhost
    #   command: ssh-copy-id -i ~/.ssh/id_rsa_ansible.pub {{ ansible_ssh_user }}@{{ inventory_hostname }}

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: {{ansible_ssh_user}}
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa_ansible.pub') }}"
