FROM almalinux:9.2

LABEL maintainer="jorge@mail.fr"
ENV TIMEZONE=Europe/Paris

RUN dnf -y update && \
    dnf -y install iproute git sshpass bind-utils tree

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3 get-pip.py && \
    pip install ansible ansible-lint

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash && \
    dnf -y install git-lfs

RUN dnf clean all && \
    pip cache purge

RUN useradd -G wheel -s /bin/bash ansible-user && \
    echo 'ansible-user:password' | chpasswd && \
    echo 'alias ll="ls --group-directories-first -phAl --color=auto"' >> /home/ansible-user/.bashrc && \
    chown -R ansible-user:ansible-user /home/ansible-user/ && \
    rm -rf /etc/localtime && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER ansible-user
WORKDIR /home/ansible-user

ENTRYPOINT ["/entrypoint.sh"]