FROM almalinux:9.2

LABEL maintainer="jorge@mail.fr"

RUN dnf -y update && \
    dnf -y install iproute git sshpass

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3 get-pip.py && \
    pip install ansible ansible-lint

RUN dnf clean all && \
    pip cache purge

RUN useradd -ms /bin/bash ansible-user && \
    echo 'ansible-user:password' | chpasswd && \
    echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    echo 'alias ll="ls --group-directories-first -phAl --color=auto"' >> /home/ansible-user/.bashrc

RUN chown -R ansible-user:ansible-user /home/ansible-user/

USER ansible-user
WORKDIR /home/ansible-user

CMD ["tail","-f","/dev/null"]