version: '3'

services:
  master:
    image: ansible_master:latest
    build: Dockerfile.ansible_master.yml
    dns: 192.168.1.1
    network_mode: bridge
    volumes:
      - .:/home/ansible-user/code