FROM centos:7

LABEL maintainer="jorge@mail.fr"

RUN yum -y update && \
    yum -y install iproute

RUN yum clean all

# RUN useradd -ms /bin/bash slave && \
#     echo 'slave:password' | chpasswd && \
#     echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
#     echo 'alias ll="ls --group-directories-first -phAl --color=auto"' >> /home/slave/.bashrc

# RUN chown -R slave:slave /home/slave/

# USER slave
# WORKDIR /home/slave

# CMD ["tail","-f","/dev/null"]