version: '3'

services:
  ansible:
    image: ansible_master:latest
    container_name: ansible
    build:
      dockerfile: ./Dockerfile.ansible_master
      context: .
    networks:
    - mynetwork
    volumes:
      - type: bind
        source: .
        target: /home/ansible-user/code
  
  slave:
    image: yum_slave:latest
    container_name: slave
    build:
      dockerfile: ./Dockerfile.slave
      context: .
    ports:
      - 22:22
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.168.56.0/24