version: '3'

services:
  master:
    image: ansible_master:latest
    container_name: ansible
    hostname: ansible-master
    build:
      dockerfile: ./Dockerfile.ansible_master.yml
      context: .
    dns: 162.168.56.1
    networks:
    - mynetwork
    volumes:
      - type: bind
        source: .
        target: /home/ansible-user/code

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 162.168.56.0/24