version: '3'

services:
  master:
    image: ansible_master:latest
    container_name: ansible
    hostname: ansible-master
    build:
      dockerfile: ./Dockerfile.ansible_master.yml
      context: .
    dns: 162.168.56.2
    network_mode: bridge
    volumes:
      - type: bind
        source: .
        target: /home/ansible-user/code