version: '3'

services:
  master:
    image: ansible_master:latest
    container_name: master
    hostname: ansible-master
    build:
      dockerfile: ./Dockerfile.ansible_master.yml
      context: .
    networks:
    - mynetwork
    volumes:
      - type: bind
        source: .
        target: /home/ansible-user/code
  
  slave-1:
    image: yum_slave:latest
    container_name: slave-1
    hostname: yum-slave
    build:
      dockerfile: ./Dockerfile.slave.yml
      context: .
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.168.56.0/24