---
# WEB SERVER
- hosts: all
  become: true

  tasks:
    - name: Check chrony
      yum:
        name:
          - chrony
        state: present

    - name: Configure chrony
      template:
        src: files/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: "0644"
    
    - name: Restart chrony
      service:
        name: chronyd
        state: restarted
