---
# TODO : le serveur ne prend pas en compte la conf, à corriger.
- name: Basic deploy
  hosts: all
  become: true

  tasks:
    - name: Install chrony
      ansible.builtin.dnf:
        name: chrony
        state: present

    - name: Deploy config file
      ansible.builtin.template:
        src: ../files/chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Chrony server
      ansible.builtin.service:
        name: chronyd
        state: restarted
