---
- name: Mise à jour des paquets
  hosts: all
  become: true

  tasks:
    - name: Mise à jour
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_only: true

    - name: Nettoyage
      ansible.builtin.dnf:
        autoremove: true
